export const PER_STUDENT_UNIT_PRICE_GNF = 50_000;
export const PER_STUDENT_SCHOOL_SHARE_GNF = 15_000;
export const PER_STUDENT_PLATFORM_SHARE_GNF = 35_000;
export const PER_STUDENT_ACCESS_THRESHOLD = 20;
